### **Import library & dataset**

In [1]:
import pandas as pd
df = pd.read_csv("D:/Fake Job Posting Dataset/fake_job_postings.csv")

### **Sample data**

In [2]:
df.head()

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

### **Data information**

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17880 entries, 0 to 17879
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   job_id               17880 non-null  int64
 1   title                17880 non-null  object
 2   location             17534 non-null  object
 3   department           6333 non-null   object
 4   salary_range         2868 non-null   object
 5   company_profile      14572 non-null  object
 6   description          17879 non-null  object
 7   requirements         15184 non-null  object
 8   benefits             10668 non-null  object
 9   telecommuting        17880 non-null  int64
 10  has_company_logo     17880 non-null  int64
 11  has_questions        17880 non-null  int64
 12  employment_type      14409 non-null  object
 13  required_experience  10830 non-null  object
 14  required_education   9775 non-null   object
 15  industry             12977 non-null  object
 16  function             11425 non-null  object
 17  fraudulent           17880 non-null  int64
dtypes: int64(5), object(13)
memory usage: 2.5+ MB

In [4]:
df.describe(include='all')

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
count,17880.000000,17880,17534,6333,2868,14572,17879,15184,10668,17880.000000,17880.000000,17880.000000,14409,10830,9775,12977,11425,17880.000000
unique,NaN,11231,3105,1337,874,1709,14801,11965,6203,NaN,NaN,NaN,5,7,13,131,37,NaN
top,NaN,English Teacher Abroad,"GB, LND, London",Sales,0-0,We help teachers get safe &amp; secure jobs ab...,"Play with kids, get paid for it Love travel? J...",University degree required. TEFL / TESOL / CEL...,See job description,NaN,NaN,NaN,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,Information Technology,NaN
freq,NaN,311,718,551,142,726,379,410,726,NaN,NaN,NaN,11620,3809,5145,1734,1749,NaN
mean,8940.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.042897,0.795302,0.491723,NaN,NaN,NaN,NaN,NaN,0.048434
std,5161.655742,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.202631,0.403492,0.499945,NaN,NaN,NaN,NaN,NaN,0.214688
min,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
25%,4470.750000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
50%,8940.500000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,0.000000,NaN,NaN,NaN,NaN,NaN,0.000000
75%,13410.250000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,0.000000
max,17880.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,1.000000

### **Null value checking**

In [5]:
df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [6]:
((df.isnull().sum()/len(df))*100).round(2)

job_id                  0.00
title                   0.00
location                1.94
department             64.58
salary_range           83.96
company_profile        18.50
description             0.01
requirements           15.08
benefits               40.34
telecommuting           0.00
has_company_logo        0.00
has_questions           0.00
employment_type        19.41
required_experience    39.43
required_education     45.33
industry               27.42
function               36.10
fraudulent              0.00
dtype: float64

### **Duplicate value checking**

In [7]:
df.duplicated().sum()

np.int64(0)

### **Checking unique values in categorical columns**

In [8]:
print(df['employment_type'].unique())

['Other' 'Full-time' nan 'Part-time' 'Contract' 'Temporary']

In [9]:
print(df['required_experience'].unique())

['Internship' 'Not Applicable' nan 'Mid-Senior level' 'Associate'
 'Entry level' 'Executive' 'Director']

In [10]:
print(df['required_education'].unique())

[nan "Bachelor's Degree" "Master's Degree" 'High School or equivalent'
 'Unspecified' 'Some College Coursework Completed' 'Vocational'
 'Certification' 'Associate Degree' 'Professional' 'Doctorate'
 'Some High School Coursework' 'Vocational - Degree'
 'Vocational - HS Diploma']

In [11]:
print(df['industry'].unique())

[nan 'Marketing and Advertising' 'Computer Software'
 'Hospital & Health Care' 'Online Media'
 'Information Technology and Services' 'Financial Services'
 'Management Consulting' 'Events Services' 'Internet'
 'Facilities Services' 'Consumer Electronics' 'Telecommunications'
 'Consumer Services' 'Construction' 'Oil & Energy' 'Education Management'
 'Building Materials' 'Banking' 'Food & Beverages' 'Food Production'
 'Health, Wellness and Fitness' 'Insurance' 'E-Learning' 'Cosmetics'
 'Staffing and Recruiting' 'Venture Capital & Private Equity'
 'Leisure, Travel & Tourism' 'Human Resources' 'Pharmaceuticals' 'Farming'
 'Legal Services' 'Luxury Goods & Jewelry' 'Machinery' 'Real Estate'
 'Mechanical or Industrial Engineering'
 'Public Relations and Communications' 'Consumer Goods' 'Medical Practice'
 'Electrical/Electronic Manufacturing' 'Hospitality' 'Music'
 'Market Research' 'Automotive' 'Philanthropy' 'Utilities'
 'Primary/Secondary Education' 'Logistics and Supply Chain' 'Design'
 'Gambling & Casinos' 'Accounting' 'Environmental Services'
 'Mental Health Care' 'Investment Management' 'Apparel & Fashion'
 'Media Production' 'Publishing' 'Medical Devices' 'Information Services'
 'Retail' 'Sports' 'Computer Games' 'Chemicals' 'Aviation & Aerospace'
 'Business Supplies and Equipment' 'Program Development'
 'Computer Networking' 'Biotechnology' 'Civic & Social Organization'
 'Religious Institutions' 'Warehousing' 'Airlines/Aviation'
 'Writing and Editing' 'Restaurants' 'Outsourcing/Offshoring'
 'Transportation/Trucking/Railroad' 'Wireless' 'Investment Banking'
 'Nonprofit Organization Management' 'Libraries' 'Computer Hardware'
 'Broadcast Media' 'Printing' 'Graphic Design' 'Entertainment' 'Wholesale'
 'Research' 'Animation' 'Government Administration' 'Capital Markets'
 'Computer & Network Security' 'Semiconductors'
 'Security and Investigations' 'Architecture & Planning' 'Maritime'
 'Fund-Raising' 'Higher Education' 'Renewables & Environment'
 'Motion Pictures and Film' 'Law Practice' 'Government Relations'
 'Packaging and Containers' 'Sporting Goods' 'Mining & Metals'
 'Import and Export' 'International Trade and Development'
 'Professional Training & Coaching' 'Textiles' 'Commercial Real Estate'
 'Law Enforcement' 'Package/Freight Delivery'
 'Translation and Localization' 'Photography' 'Industrial Automation'
 'Wine and Spirits' 'Public Safety' 'Civil Engineering' 'Military'
 'Defense & Space' 'Veterinary' 'Executive Office' 'Performing Arts'
 'Individual & Family Services' 'Public Policy' 'Nanotechnology'
 'Museums and Institutions' 'Fishery' 'Plastics' 'Furniture'
 'Shipbuilding' 'Alternative Dispute Resolution' 'Ranching']

In [12]:
print(df['function'].unique())

['Marketing' 'Customer Service' nan 'Sales' 'Health Care Provider'
 'Management' 'Information Technology' 'Other' 'Engineering'
 'Administrative' 'Design' 'Production' 'Education' 'Supply Chain'
 'Business Development' 'Product Management' 'Financial Analyst'
 'Consulting' 'Human Resources' 'Project Management' 'Manufacturing'
 'Public Relations' 'Strategy/Planning' 'Advertising' 'Finance'
 'General Business' 'Research' 'Accounting/Auditing' 'Art/Creative'
 'Quality Assurance' 'Data Analyst' 'Business Analyst' 'Writing/Editing'
 'Distribution' 'Science' 'Training' 'Purchasing' 'Legal']

In [13]:
print(df['department'].unique())

['Marketing' 'Success' nan ... 'Admin - Clerical' 'Administrative Dept'
 'Hospitality']

### **Replacing null values of categorical columns**

In [14]:
df['employment_type'] = df['employment_type'].fillna('Unknown')
df['required_experience'] = df['required_experience'].fillna('Not Specifed') 
df['required_education'] = df['required_education'].fillna('Not Specifed')
df['function'] = df['function'].fillna('Unknown Function')
df['industry'] = df['industry'].fillna('Unknown Industry')
df['department'] = df['department'].fillna('Unknown Department')

### **Checking values**

In [15]:
df.isnull().sum()

job_id                     0
title                      0
location                 346
department                 0
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type            0
required_experience        0
required_education         0
industry                   0
function                   0
fraudulent                 0
dtype: int64

### **Replacing null values**

In [16]:
df['location'].str.contains('US', na=False).sum()

np.int64(10656)

In [17]:
((df['location'].str.contains('US', na=False).sum()/len (df))*100).round(2)

np.float64(59.6)

In [18]:
df['salary_range'] = df['salary_range'].fillna('Not Specified')

In [19]:
df['location'] = df['location'].fillna('Unknown Location')
df['company_profile'] = df['company_profile'].fillna('No Company Profile Provided') 
df['description'] = df['description'].fillna('Not Available')
df['requirements'] = df['requirements'].fillna('Not Specified')
df['benefits'] = df['benefits'].fillna('Not Specified')

### **Checking values**

In [20]:
df.isnull().sum()

job_id                 0
title                  0
location               0
department             0
salary_range           0
company_profile        0
description            0
requirements           0
benefits               0
telecommuting          0
has_company_logo       0
has_questions          0
employment_type        0
required_experience    0
required_education     0
industry               0
function               0
fraudulent             0
dtype: int64

---
# Part 2: Exploratory Data Analysis (EDA)
---

### **Understand target variables**

In [21]:
total_jobs = len(df)
real_jobs = (df['fraudulent'] == 0).sum() 
fake_jobs = (df['fraudulent'] == 1).sum() 
fraud_percentage = (fake_jobs / total_jobs)*100

In [22]:
print("Total Jobs:", total_jobs)
print("Real Jobs:", real_jobs)
print("Fake Jobs:", fake_jobs)
print("Fraud Percentage:", round(fraud_percentage,2), "%")

Total Jobs: 17880
Real Jobs: 17014
Fake Jobs: 866
Fraud Percentage: 4.84 %

---
# Part 3: Connecting to SQL
---

In [23]:
!pip install pymysql sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pymysql in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (1.2.0)
Requirement already satisfied: sqlalchemy in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (2.0.50)
Requirement already satisfied: greenlet>=1 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (3.5.1)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\User\AppData\Roaming\Python\Python313\site-packages (from sqlalchemy) (4.15.0)

[notice] A new release of pip is available: 26.1.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [24]:
from sqlalchemy import create_engine

# Format: mysql+pymysql://username:password@host:port/database_name
# Replace 'YOUR_PASSWORD' with your actual MySQL Workbench password
engine = create_engine("mysql+pymysql://root:180104@localhost:3306/fake_job_analytics")

In [25]:
# Replace 'cleaned_project_table' with whatever you want to name your SQL table
df.to_sql(name='fake_job', con=engine, if_exists='replace', index=False)

print("Data successfully sent to MySQL!")

Data successfully sent to MySQL!